service: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  httpApi:
    cors: true
  environment:
    DB_HOST: task4.cwmy3wmvakix.us-east-1.rds.amazonaws.com
    DB_PORT: 5432
    DB: shop
    DB_USER: postgres
    DB_PASSWORD: vnZmqzVOhkUMhI2N4Nx6

functions:
  getAllProducts:
    handler: src/getAll.getAll
    events:
      - httpApi:
          method: GET
          path: /products
  getProductsById:
    handler: src/getById.getById
    events:
      - httpApi:
          method: GET
          path: /products/{productId}
  createProduct:
    handler: src/createProduct.createProduct
    events:
      - httpApi:
          method: POST
          path: /products