service: product-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-central-1
  httpApi:
    cors: true

functions:
  getAllProducts:
    handler: src/getAll.getAll
    events:
      - httpApi:
          method: GET
          path: /products
  getProductsById:
    handler: src/getById.getById
    events:
      - httpApi:
          method: GET
          path: /products/{productId}