service: import-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  environment:
    SQS_URL:
      Ref: catalogItemsQueue
  iam:
    role:
      statements:
        - Effect: Allow
          Action: sqs:*
          Resource:
            - Fn::GetAtt:
                - catalogItemsQueue
                - Arn
        - Effect: Allow
          Action: sns:*
          Resource:
            Ref: createProductTopic
        - Effect: Allow
          Action: "s3:ListBucket"
          Resource:
          - '*'
        - Effect: Allow
          Action: 
            - "s3:*"
          Resource:
          - 'arn:aws:s3:::import-service-uz-task5/*'

resources:
  Resources:
    catalogItemsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: catalogItemsQueue
    createProductTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: rss-aws-sns-topic
    SNSSubscription:
      Type: AWS::SNS::Subscription
      Properties:
        Protocol: email
        Endpoint: test@gmail.com
        TopicArn:
          Ref: createProductTopic

    

functions:
  importProductsFile:
    handler: importFile.importFile
    events:
      - http:
          method: get
          path: /import
          cors: true
          request:
            parameters:
              querystrings:
                name: true
  getFiles:
    handler: importFile.readFiles
    events:
      - http:
          method: get
          path: /products
          cors: true
  importFileParser:
    handler: fileParser.fileParser
    events:
      - s3:
          bucket: "import-service-uz-task5"
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true
  catalogBatchProcess:
    handler: catalogBatchProcess.batch
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - catalogItemsQueue
              - Arn
          batchSize: 10