service: import-service
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name
frameworkVersion: '3'

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action: "s3:ListBucket"
          Resource:
          - '*'
        - Effect: Allow
          Action: 
            - "s3:*"
          Resource:
          - 'arn:aws:s3:::import-service-uz-task5/*'

functions:
  importProductsFile:
    handler: importFile.importFile
    events:
      - http:
          method: get
          path: /import
          cors: true
          request:
            parameters:
              querystrings:
                name: true

